### ISSUE TITLE
gem源问题

### ISSUE THREAD

**Issue by yueysheng** [ruby-china/rubygems-mirror#105]
gems源网站在电脑上可以访问，但是执行gem update --system 时无法更新，gem版本2.6.14

**Comment by 1218ZLWang** [comment]
w@ubuntu:~/CourseSelect$ bundle install
Fetching source index from https://gems.ruby-china.org/

Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://gems.ruby-china.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://gems.ruby-china.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://gems.ruby-china.org/
Could not fetch specs from https://gems.ruby-china.org/



修改为
w@ubuntu:~/CourseSelect$ gem sources -l
*** CURRENT SOURCES ***

https://gems.ruby-china.com
还是不能运行
