### ISSUE TITLE
https://gems.ruby-china.org/specs.4.8.gz 不可下载

### ISSUE THREAD

**Issue by bachue** [ruby-china/rubygems-mirror#87]
来自 CI 里的错误：

```
$ gem sources --remove https://rubygems.org/
https://rubygems.org/ removed from sources
$ gem sources --add https://gems.ruby-china.org/
Error fetching https://gems.ruby-china.org/:
	server did not return a valid file (https://gems.ruby-china.org/specs.4.8.gz)
```

然后我去尝试 wget https://gems.ruby-china.org/specs.4.8.gz 这个文件，果然不能下载。请帮忙看下。
谢谢

![image](https://user-images.githubusercontent.com/321962/30192688-8a96e7d0-947b-11e7-95f5-b7ec4b5d2c6d.png)

**Comment by vy0b0x** [comment]
+1

**Comment by Jesse-Fan** [comment]
+1

**Comment by tffire** [comment]
+1,求解

**Comment by caiyuan623** [comment]
+1   Error fetching https://gems.ruby-china.org/:
	server did not return a valid file (https://gems.ruby-china.org/specs.4.8.gz)

**Comment by huacnlee** [comment]
看起来已经好了

**Comment by caiyuan623** [comment]
正解

**Comment by bachue** [comment]
@huacnlee 好像是好了

**Comment by Jesse-Fan** [comment]
Updating installed gems
ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    no such name (https://gems.ruby-china.org/specs.4.8.gz)

**Comment by Lupeipei** [comment]
+1, 求解，依然是：server did not return a valid file (https://gems.ruby-china.org/latest_specs.4.8.gz)

**Comment by yinchuan9527** [comment]
gem sources -a https://gems.ruby-china.com/

**Comment by shuiRong** [comment]
![image](https://user-images.githubusercontent.com/16076993/58688481-24226b00-83b7-11e9-803a-5fcedbe67a5c.png)

same here.

```
Error fetching https://gems.ruby-china.com/:
        no such name (https://gems.ruby-china.com/specs.4.8.gz)
```

**Comment by czhan141-ford** [comment]
> ![image](https://user-images.githubusercontent.com/16076993/58688481-24226b00-83b7-11e9-803a-5fcedbe67a5c.png)
> 
> same here.
> 
> ```
> Error fetching https://gems.ruby-china.com/:
>         no such name (https://gems.ruby-china.com/specs.4.8.gz)
> ```
> 
> so anyone knows?

So did you resolve this issue?

**Comment by sharly2012** [comment]
I also have this issue. 

admindeMacBook-Pro:~ admin$ sudo gem install cocoapods
ERROR:  Could not find a valid gem 'cocoapods' (>= 0), here is why:
          Unable to download data from https://gems.ruby-china.com/ - no such name (https://gems.ruby-china.com/specs.4.8.gz)

Anyone knows how fix ?

**Comment by huacnlee** [comment]
由于备案被注销，还得重新走流程。

最近 RubyGems 镜像稳定性会受影响，当前 UpYun 把 gems.ruby-china.com 解析到境外（欧洲）的服务器上了，所以用起来会有一些问题，等月底备案问题解决才会恢复

**Comment by jins21** [comment]
> I also have this issue.
> 
> admindeMacBook-Pro:~ admin$ sudo gem install cocoapods
> ERROR: Could not find a valid gem 'cocoapods' (>= 0), here is why:
> Unable to download data from https://gems.ruby-china.com/ - no such name (https://gems.ruby-china.com/specs.4.8.gz)
> 
> Anyone knows how fix ?

Did it fix ？ can you share your method ，please？

**Comment by lixiaoyu** [comment]
Fetching gem metadata from https://gems.ruby-china.com/...
Retrying dependency api due to error (2/4): Bundler::HTTPError Network error while fetching https://gems.ruby-china.com/api/v1/dependencies?gems=autoparse%2Caws-sdk-athena%2Caws-sdk-core%2Caws-sdk-lex%2Caws-sdk-marketplaceentitlementservice%2Caws-sdk-organizations%2Caws-sdk-resourcegroupstaggingapi%2Caws-sdk-states%2Caws-sdk-workdocs%2Caws-sigv4%2Ccelerity%2Ccertified%2Cchildprocess%2Cculerity%2Cdatabase_cleaner%2Cdigest-crc%2Cdotenv-deployment%2Cextlib%2Cgoogle-apis-core%2Cgoogle-apis-generator%2Cgoogle-apis-iamcredentials_v1%2Cgoogle-apis-storage_v1%2Cgoogle-cloud-core%2Cgoogleauth%2Chttpadapter%2Churley%2Claunchy%2Cliquid%2Cmechanize%2Cmemoist%2Cmimemagic%2Cmini_mime%2Cmsgpack%2Coauth2%2Crack-test%2Cregexp_parser%2Crepresentable%2Cretriable%2Croauth%2Cselenium-webdriver%2Csignet%2Csinatra%2Csnappy%2Csubexec%2Cterm-ansicolor%2Ctermios%2Cthor%2Cuglifier%2Cvirtus%2Cxpath (Net::ReadTimeout)

**Comment by Katherinaxxx** [comment]
I fixed the solution here [https://gems.ruby-china.com/](url)
